{{- if .Values.ingress.redirectHttps }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Chart.Name }}-redirect-https
spec:
  redirectScheme:
    scheme: https
    permanent: true
{{- end }}
