apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
type: Opaque
stringData:
  NOTION_API_KEY: {{ .Values.env.notionApiKey | quote }}
  GEMINI_API_KEY: {{ .Values.env.geminiApiKey | quote }}
  SERPER_API_KEY: {{ .Values.env.serperApiKey | quote }}
